---
title: "CovidResearch"
output:
  html_document: default
  pdf_document: default
---
## Install and load Libraries
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#install.packages('dplyr')
library(readr)
library(dplyr)
library(ggplot2)
library(lubridate)
options(scipen=999)
```
## We used the datasets
## Import Data
```{r}
#Covid-19 Info
cov_general_data<- read_csv2("../datasets/COVID-19_aantallen_gemeente_cumulatief.csv")
cov_hospital_data <- read_csv2("../datasets/COVID-19_ziekenhuisopnames.csv")
#Other info
res_count_per_province_nl <- read_csv2("../datasets/Bevolkings_aantallen_per_provincie.csv")
```

## Population per province compared to the positive tests, hospital admissions and deaths per province

```{r}
## lets first inspect the datasets
cov_general_data
cov_hospital_data
res_count_per_province_nl
```

## Let's explain the relevant variables and why/how we are going to use them
## TODO:
## Glenn: cov_general_data cleaning
## Jamie: cov_hosp_data cleaning

```{r}
## The first dataset (cov_general_data) has to be cleaned up, because it has missing values and only the latest report data needs to be filtered out.
## Let's first filter the data based on the latest publication we have
## TODO: Here filter the cov_general_data by the date of 10th of March, 2022
## create a new variable named 'cov_general_data_clean' which represents the filtered dataset that shows the date of report of 10th of March, 2022
cov_general_data$Date_of_report <- as.Date(cov_general_data$Date_of_report, format="%m/%d/%y")
cov_general_data_clean <- filter(cov_general_data, Date_of_report == "2022-3-10")
cov_general_data_clean
```

```{r}
## Let's filter out the null values from cov_general_data where the province is null since we cant use those in our research
## TODO: Here filter out the null values from cov_general_data_clean
## TODO: new explaination

cov_general_data_clean <- filter(cov_general_data_clean,!is.na(Province))
cov_general_data_clean
```

```{r}
## A double entry of province has been detected in the cov_general_data_clean which needs to be combined
## TODO: Here combine the values 'Friesland' and 'Fryslân'
cov_general_data_clean <- cov_general_data_clean %>%
  mutate(Province = replace(Province, Province == "Fryslân", "Friesland"))
cov_general_data_clean
```

```{r}
## Remove variables that we are not going to use from cov_general_data
## TODO: Here remove Municipality_name, Municipality_code and Hospital Admission from cov_general_data
cov_general_data_clean$Municipality_name <- NULL
cov_general_data_clean$Municipality_code <- NULL
cov_general_data_clean$Hospital_admission <- NULL

cov_general_data_clean
```

```{r}
## Filter null values out of the dataset cov_hospital_data_clean
## TODO: Here filter out the rows where the is Security_region_name not available
## Making a new cleaned tibble called cov_hospital_data_clean
cov_hospital_data_clean <- filter(cov_hospital_data, !is.na(Security_region_name))
cov_hospital_data_clean 
```

```{r}
## Rename 'Fryslân' to 'Friesland' in cov_hospital_data
## TODO: Here rename 'Fryslân' to 'Friesland' for consistency sake.
cov_hospital_data_clean <- cov_hospital_data_clean %>%
  mutate(Security_region_name = replace(Security_region_name, Security_region_name == "Fryslân", "Friesland"))
cov_hospital_data_clean

```

```{r}
## Combine security regions into their respective provinces to a province variable to better fit the resident count data for later.
## Sorted based off this article wiki https://en.wikipedia.org/wiki/Safety_region
## TODO: Create Sets categorizing the security regions into their respective provinces
# only these provinces are fragmented the others are fine.
overijssel_vr <- c("VR04","VR05")
gelderland_vr <- c("VR06","VR07","VR08")
north_holland_vr <- c("VR10","VR11","VR12","VR13","VR14")
south_holland_vr <- c("VR15","VR16","VR17","VR18")
north_brabant_vr <- c("VR20","VR21","VR22")
limburg_vr <- c("VR23","VR24")
## TODO: Here combine security regions into their respective province
cov_hospital_data_clean <- cov_hospital_data_clean %>%
  mutate(Province = case_when(
    Security_region_code %in% overijssel_vr ~ 'Overijssel',
    Security_region_code %in% gelderland_vr ~ 'Gelderland',
    Security_region_code %in% north_holland_vr ~ 'Noord-Holland',
    Security_region_code %in% south_holland_vr ~ 'Zuid-Holland',
    Security_region_code %in% north_brabant_vr ~ 'Noord-Brabant',
    Security_region_code %in% limburg_vr ~ 'Limburg',
    TRUE ~ Security_region_name))

cov_hospital_data_clean
```


```{r}
## Remove variables that we are not going to use from cov_hospital_data_clean
## TODO: Here remove 'Municipality_code', 'Municipality_name', 'Security_region_code', Security_region_name from cov_hospital_data_clean
cov_hospital_data_clean$Municipality_name <- NULL
cov_hospital_data_clean$Municipality_code <- NULL
cov_hospital_data_clean$Security_region_code <- NULL
cov_hospital_data_clean$Security_region_name <- NULL

cov_hospital_data_clean
```
